services:
  cagnotte:
    image: ghcr.io/cytrig/cagnotte:latest
    container_name: cagnotte
    environment:
      - TZ=Europe/Paris
    volumes:
      - /mnt/Main/Apps/Apps_Data/cagnotte:/data
    ports:
      - 30060:8000 
    restart: unless-stopped
